version: "3.3"

services:
  app:
    build: ./
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app/server
      - ./pages:/usr/src/app/pages
      - ./store:/usr/src/app/store
      - ./components:/usr/src/app/components
      - ./layouts:/usr/src/app/layouts
      - ./assets:/usr/src/app/assets
    env_file:
      - .env

